export default {
    LOGIN: "/api/admin/login",
    CHANGE: "/api/admin/update",
    getexpersData: "/api/admin/getexpersData",
    GETCHANGEDATA: "/api/admin/getChangeData",
    GETROOTDATA: "/api/admin/getRootData",
    updateExpertsProject: "/api/admin/updateExpertsProject",
    REGISTERED: "/api/admin/registered",
    beforeRegistered: "/api/admin/beforeRegistered",
    DELETEUSER: "/api/admin/deleteUser",
    UPLOAD: "/api/upload/upload",
    UPLOADFILE: "/api/upload/uploadFile",
    USER: "/api/user/user",
    DEPARTMENT: "/api/department/department",
    CATEGORY: "/api/category/category",
    PROJECT: "/api/project/project",
    PROJECT_TYPE: "/api/project_type/projectType",
    RESETPASS:"/api/admin/resetPass",
    COLLEGE:"/api/college/college",
    UPDATERESEARCHPROJECT:"/api/admin/updateResearchProject",
    GETRESEARCHPROJECT:"/api/admin/getResearchProject",
    UPDATERESEARCHPROJECT1:"/api/admin/updateProject",
    GETEXPERTSDATA:"/api/admin/getExpertsData",
    NEWS:"/api/News/News",
    SCHOOLNEWS:"/api/SchoolNews/SchoolNews",
    NOTICE:"/api/Notice/Notice",
    MEETING:"/api/Meeting/Meeting",
}